name = "sink"
pages_build_output_dir = "dist"
upload_source_maps = true
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 3000

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "5d319286bfd54dbeac64a63c23487a12"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "sink"
